### ISSUE TITLE
Support both Gemfile syntaxes for ruby-version

### ISSUE THREAD

**Issue by jrep** [senny/rvm.el#43]
When ruby-version is taken from Gemfile, [three syntaxes](http://rvm.io/workflow/projects) are supported:

    #ruby=2.1.0
    ruby "2.1.0"
    ruby '2.1.0'

Currently, rvm.el only recognizes the comment form. But the directive form(s) mean something to Bundler, and should also be allowed.

**Comment by senny** [comment]
Implemented by #44
