### ISSUE TITLE
rvm-use selecting "(default)" gemset doesn't properly set the path

### ISSUE THREAD

**Issue by jjrussell** [senny/rvm.el#51]
Because `rvm gemset list_all` returns "(default)" as one of the options, including the parens, that is what `rvm/gemset-list` returns as one of the options. If that is selected then the `rvm-use` function eventually calls `rvm/info` with a gemset of `(default)` to get ruby info to get the path to the ruby command to add to the path. Since it can't find the gemset it returns the ruby info for the current selected ruby, not necessarily the one you are changing to.

**Comment by senny** [comment]
@jjrussell thank you for reporting. This doesn't sound right.

Since I've open sourced this package I moved on to using rbenv. Would you be interested in working on the patch?

**Comment by jjrussell** [comment]
I'll give it a try. There are rumblings that we might be moving to rbenv. Is there a corresponding emacs project for that? This one has been a life saver for rvm.

**Comment by senny** [comment]
@jjrussell yes, there is. I started [`rbenv.el`](https://github.com/senny/rbenv.el) when I switched.
