### ISSUE TITLE
This project is looking for a new maintainer

### ISSUE THREAD

**Issue by senny** [senny/rvm.el#52]
Since I've started this project I have switched to rbenv. There is still an occasional bug and possible improvements (#46), which didn't get the attention they deserve.

If you are using this package and are interested in contributing or even maintaining it, please respond or contact me :yellow_heart: .

**Comment by cosmonaut-ok** [comment]
Hi, Senny. I can do it. I'm using emacs and rvm, so can maintain this project

**Comment by sshaw** [comment]
@cosmonaut-ok are you now the maintainer?

**Comment by sshaw** [comment]
Well if he's not, I can be.

**Comment by senny** [comment]
@sshaw great to hear. I'll grant you the necessary permissions. Let me know if you have any questions.

**Comment by sshaw** [comment]
Great thanks. If you have any unstated thoughts on existing issues that'd be great to hear (#55 maybe 😈). Otherwise I'll dig into the codebase and issues over the next week and let you know if I have any questions.
