### ISSUE TITLE
rvm-activate-corresponding-ruby extremely slow on OSX

### ISSUE THREAD

**Issue by AshtonKem** [senny/rvm.el#54]
I'm currently using spacemacs on OSX (10.11.6) using Emacs 25.1.1. Running ```rvm-activate-corresponding-ruby``` takes up to 8 seconds on my machine, which is just far too slow to be added to a mode-hook or similar.

**Comment by sshaw** [comment]
Hi @AshtonKem, 

Are you seeing this when use run the command interactively? 

What file contains your ruby version (`Gemfile`, `.ruby-info`, ...)?

Do you see this when running it from a shallow directory structure?

**Comment by sshaw** [comment]
Note that the 1.4.1 added an additional check using `bundle config`. Would be interested in knowing if this causes additional slowdown for you.

**Comment by AshtonKem** [comment]
Sorry, I stopped using Emacs quite a while ago. Won't be able to meaningfully reproduce this anymore.
